import { Octokit } from "@octokit/rest";
import Anthropic from "@anthropic-ai/sdk";
import { type Agent, type AgentResult } from "./base";
import { type PullRequestPayload, pullRequestPayloadSchema } from "../triggers/github";
import { setupGitCredentials } from "../lib/gitCredentials";
import { buildFileList } from "../lib/repoHelpers";

export const reviewPRAgent: Agent<PullRequestPayload> = {
  name: "reviewPR",
  inputSchema: pullRequestPayloadSchema,
  tools: [],

  async run(input, ctx): Promise<AgentResult> {
    const { sandbox, githubToken, anthropicApiKey } = ctx;
    const pr = input.pull_request;
    const repo = input.repository;
    const octokit = new Octokit({ auth: githubToken });
    const anthropic = new Anthropic({ apiKey: anthropicApiKey });
    const artifacts: string[] = [];

    try {
      await octokit.issues.createComment({
        owner: repo.owner.login,
        repo: repo.name,
        issue_number: pr.number,
        body: "Code review in progress...",
      });

      // Fix: use credential helper — no token in clone URL
      const cloneUrl = await setupGitCredentials(
        sandbox,
        githubToken,
        repo.owner.login,
        repo.name,
      );

      await sandbox.exec(
        `git clone --depth=1 --branch=${pr.head.ref} ${cloneUrl} /workspace/repo`,
      );

      const comparison = await octokit.repos.compareCommits({
        owner: repo.owner.login,
        repo: repo.name,
        base: pr.base.sha,
        head: pr.head.sha,
      });

      // Fix: use buildFileList helper
      const fileList = buildFileList(comparison.data.files || []);
      const filesWithContent = [];
      for (const f of fileList) {
        const file = await sandbox.readFile(`/workspace/repo/${f.path}`);
        filesWithContent.push({ path: f.path, patch: f.patch, content: file.content });
      }

      // Fix: model claude-sonnet-4-6
      const response = await anthropic.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 2048,
        messages: [
          {
            role: "user",
            content: `Review this PR:

              Changed files:
              ${filesWithContent.map((f) => `File: ${f.path}\nDiff:\n${f.patch}\n\nContent:\n${f.content.substring(0, 1000)}`).join("\n\n")}

              Provide a brief code review focusing on bugs, security, and best practices.`,
          },
        ],
      });

      const review =
        response.content[0]?.type === "text"
          ? response.content[0].text
          : "No review generated";

      await octokit.issues.createComment({
        owner: repo.owner.login,
        repo: repo.name,
        issue_number: pr.number,
        body: `## Code Review\n\n${review}\n\n---\n*Generated by Claude*`,
      });

      artifacts.push(`PR #${pr.number} review posted`);
      artifacts.push(review);

      return {
        success: true,
        artifacts,
        usage: response.usage
          ? { inputTokens: response.usage.input_tokens, outputTokens: response.usage.output_tokens }
          : undefined,
      };
    } catch (error: any) {
      console.error("reviewPR agent failed:", error);
      try {
        await octokit.issues.createComment({
          owner: repo.owner.login,
          repo: repo.name,
          issue_number: pr.number,
          body: `Review failed: ${error.message}`,
        });
      } catch {
        // best effort
      }
      return { success: false, artifacts, error: error.message };
    }
  },
};
